Multiple choice with year and subject
HackerSchool/HSaoQuadrado pull request #53
Opened 2021-06-15 21:13 UTC by LordOfTheNeverThere

2021-06-16 11:07 UTC, JeronimoMendes requested changes

2021-06-16 11:07 UTC, JeronimoMendes commented on exams/views.py
> +                questions = Question.objects.filter(year=subjectAndYearList[1][0]).all()
In the previews queries, you already filtered questions with the chosen year.

2021-06-16 12:55 UTC, LordOfTheNeverThere commented on exams/views.py
> +        numberOfQuestions=3
Ohh btw shouldn't numberOfQuestions be a parameter given by the user in a possible range of values. Or should all exams have a fixed value of 10 Questions?

2021-06-17 16:31 UTC, JeronimoMendes commented on exams/views.py
> +        numberOfQuestions=3
That's something we could discuss in a meeting.

2021-06-19 01:52 UTC, JeronimoMendes approved these changes

2021-06-19 09:19 UTC, merged